module.exports = [
    { original: "¡Hola! Soy el Asistente virtual", custom: "¡Hola! Soy el Asistente virtual 🤖 de la UTN Reconquista, estoy para responder a las dudas o preguntas frecuentes relacionadas con la facultad. Dime, ¿Qué necesitas saber?" },
    { original: "¿Quiere Info sobre carreras de grado", custom: "¿Quiere Info sobre carreras de grado, posgrado, carreras a distancia o tecnicaturas?🤔, escriba su respuesta" },
    { original: "Carreras de grado ✍️", custom: "Contamos con Ingeniería Electromecanica: https://www.frrq.utn.edu.ar/carreras/ie/ y con Lic. en Administración Rural: https://www.frrq.utn.edu.ar/carreras/lar/"},
    { original: "Carreras de Posgrado 👩‍🎓👨‍🎓:", custom: "Contamos con Dirección y gestión de empresas agroindustriales: https://www.frrq.utn.edu.ar/carreras/pdgea/"},
    { original: "Carreras a distancia 🌐:", custom: "Contamos con: \n Tecnicatura Universitaria en Tecnologías de la Información: https://www.frrq.utn.edu.ar/carreras/carreras-a-distancia/tuti-online/ \nLicenciatura en Tecnologías Inclusivas en Educación: https://www.frrq.utn.edu.ar/carreras/carreras-a-distancia/ltie-online/ \nTecnicatura Universitaria en Ciudades Inteligentes: https://www.frrq.utn.edu.ar/carreras/carreras-a-distancia/tuci-online/ \nTecnicatura Universitaria en Administración: https://frrq.utn.centrodeelearning.com/detalle/carrera/804/tecnicatura-universitaria-en-administracion \nLicenciatura en Logística: https://www.frrq.utn.edu.ar/carreras/carreras-a-distancia/ll-online/ \nTecnicatura Universitaria en Higiene y Seguridad en el Trabajo: https://frrq.utn.centrodeelearning.com/detalle/carrera/648/tecnicatura-universitaria-en-higiene-y-seguridad-en-el-trabajo \nLicenciatura en Tecnología Educativa: https://frrq.utn.centrodeelearning.com/detalle/carrera/1235/licenciatura-en-tecnologia-educativa \nTecnicatura Universitaria en Logística: https://frrq.utn.centrodeelearning.com/detalle/carrera/2407/tecnicatura-universitaria-en-logistica?id=999192906"},
    { original: "Tecnicaturas 👨‍💻👩‍💻:", custom: "Contamos con: \n Tecnicatura Univ. en Higiene y Seguridad en el trabajo: https://www.frrq.utn.edu.ar/carreras/tuhst/ \nTecnicatura Univ. en Mecatrónica: https://www.frrq.utn.edu.ar/carreras/tum/ \nTecnicatura Univ. en Programación: https://www.frrq.utn.edu.ar/carreras/tup/"},
    { original: "Aquí tienes enlaces para ir al módulo de autogestión 👇:", custom: "Aquí tienes enlaces para ir al módulo de autogestión 👇:\nDocente: http://www3.frrq.utn.edu.ar/sysacadweb/logindocente.asp \nAlumno: http://www3.frrq.utn.edu.ar/sysacadweb/loginalumno.asp"},
    { original: "Estas son nuestras redes sociales 💻👇:", custom: "Facebook: https://www.facebook.com/utnreconquista \n Instagram: https://www.instagram.com/utnreconquista/ \nSitio Web: https://www.frrq.utn.edu.ar/"},
    { original: "Sigue el enlace para ver donde se ubica la universidad:", custom: "Sigue el enlace para ver donde se ubica la universidad: https://maps.app.goo.gl/pvn1PmLPDrNszguv8"},
    { original: "Puedes echarle un vistazo al reglamento de estudio a través de este enlace 👇:", custom: "Puedes echarle un vistazo al reglamento de estudio a través de este enlace 👇:\nhttp://csu.rec.utn.edu.ar/docs/php/salida.php3?tipo=ORD&numero=1549&anio=0&facultad=CSU"},
    { original: "En el siguiente link podes ver las fechas con horarios de cátedras y las fechas de exámenes ✍📅:", custom: "En el siguiente link podes ver las fechas con horarios de cátedras y las fechas de exámenes ✍📅:\nHorarios: https://bit.ly/3OxZQh9"},
    { original: "Una vez inscripto al cursado, desde Alumnado se le darán los accesos a la plataforma virtual, el ingreso se realiza con el número de DNI en USUARIO y CONTRASEÑA. Aquí tienes un enlace directo a Moodle 👇:", custom: "Una vez inscripto al cursado, desde Alumnado se le darán los accesos a la plataforma virtual, el ingreso se realiza con el número de DNI en USUARIO y CONTRASEÑA. Aquí tienes un enlace directo a Moodle 👇:\nMoodle: https://frrq.cvg.utn.edu.ar"},
    { original: "Deberás ingresar al Autogestión Alumnos a través de la página de la Facultad e inscribirte a la asignatura que quieras rendir. Recuerda que puedes inscribirte o cancelar tu inscripción hasta las 13 hs. del día anterior a la fecha de examen.", custom: "Deberás ingresar al Autogestión Alumnos a través de la página de la Facultad e inscribirte a la asignatura que quieras rendir. Recuerda que puedes inscribirte o cancelar tu inscripción hasta las 13 hs. del día anterior a la fecha de examen.\nAutogestión Alumnos: http://www3.frrq.utn.edu.ar/sysacadweb/loginalumno.asp"},
    { original: "Recuerda que si eres un alumno activo en la facultad, debes inscribirte a las materias a través de tu autogestión", custom: "Recuerda que si eres un alumno activo en la facultad, debes inscribirte a las materias a través de tu autogestión (la inscripción no se realiza de manera automática, así que deberás inscribirte al cursado de las asignaturas ANTES del inicio de cada cuatrimestre). Si no sabes tu legajo y/o tu contraseña o si no sabes como operar la interfaz de autogestión, comuníquese con alumnado:  📱  3482 – 751911 (Celular) // 📞  3482 – 420048 Int. 8201 (de 9 a 21 hs) // 📧  auxalumnado@frrq.utn.edu.ar (correo)\nAutogestión Alumnos: http://www3.frrq.utn.edu.ar/sysacadweb/loginalumno.asp"},
    { original: "La universidad dispone de una amplia variedad de cursos online, todos tienen un costo a abonar por cuotas. Para saber sobre el tipo de curso y su costo, más información adicional, ingrese a los siguientes enlaces 👇:", custom: "La universidad dispone de una amplia variedad de cursos online, todos tienen un costo a abonar por cuotas. Para saber sobre el tipo de curso y su costo, más información adicional, ingrese a los siguientes enlaces 👇:\nAprender Online UTN: https://aprenderonline.frrq.utn.edu.ar \nCentro de learning UTN: https://frrq.utn.centrodeelearning.com"}
];